
server:
  port: 8080
spring:
  application:
    name: Agumon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/agumon
    username: root
    password: root

#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#  discovery:
#    server-addr: 127.0.0.1:8848

mybatis:
  config-locations: classpath:/mapper/mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

